// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab09webAPp.Data;

#nullable disable

namespace lab09webAPp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251211222712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lab09webAPp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 11, 22, 27, 11, 638, DateTimeKind.Utc).AddTicks(8316),
                            Description = "High-performance laptop",
                            Name = "Laptop",
                            Price = 3999.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 12, 11, 22, 27, 11, 638, DateTimeKind.Utc).AddTicks(8318),
                            Description = "Wireless gaming mouse",
                            Name = "Mouse",
                            Price = 199.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 12, 11, 22, 27, 11, 638, DateTimeKind.Utc).AddTicks(8320),
                            Description = "Mechanical keyboard",
                            Name = "Keyboard",
                            Price = 399.99m,
                            StockQuantity = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
